FROM prom/prometheus

ADD prometheus.yml /etc/prometheus/

# docker rm --force prometheus-custom
# docker build -t prometheus-custom .
# docker run --name prometheus-custom -p 9090:9090 prometheus-custom

# docker rm --force prometheus-custom && docker build -t prometheus-custom . && docker run --name prometheus-custom -p 9090:9090 prometheus-custom